<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <AssemblyName>FlamesCLI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flames\Flames_dotnet_dev.csproj" />
  </ItemGroup>
</Project>
