<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <DefineConstants>$(DefineConstants);F_STANDALONE;CORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flames\Flames_standalone_dev.csproj" />
  </ItemGroup>
</Project>
