name: Build dotnet dev
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - debug
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.ref }}-dev
  cancel-in-progress: true

jobs:
#============================================
# ============== .NET 6.0 BUILD =============
# ===========================================
  build-dotnet6:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore CLI/FlamesCLI_dotnet6_dev.csproj
      - name: Build
        id: compile
        run: |
          dotnet build CLI/FlamesCLI_dotnet6_dev.csproj --no-restore
        
      - uses: ./.github/actions/notify_failure_harmony
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Flames dotnet dev build!'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success_harmony
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'CLI/bin/Debug/net6.0'
          DEST_NAME: 'Flames-net6.0'
          NOTIFY_MESSAGE: 'Successfully compiled Flames dotnet dev build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          DELETE_AFTER: '1'
          
      # publish standalone windows binaries
      - name: Publish-win64
        run: dotnet publish CLI/FlamesCLI_standalone6_dev.csproj -r win-x64 --self-contained
          
      - uses: ./.github/actions/notify_success_harmony
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'CLI/bin/Debug/net6.0/win-x64/publish'
          DEST_NAME: 'Flames-win64-standalone'
          NOTIFY_MESSAGE: 'Successfully compiled Flames Windows 64-bit standalone dev build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          DELETE_AFTER: '1'

          
      # publish standalone linux binaries
      - name: Publish-linux64
        run: dotnet publish CLI/FlamesCLI_standalone6_dev.csproj -r linux-x64 --self-contained
          
      - uses: ./.github/actions/notify_success_harmony
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'CLI/bin/Debug/net6.0/linux-x64/publish'
          DEST_NAME: 'Flames-linux64-standalone'
          NOTIFY_MESSAGE: 'Successfully compiled Flames Linux 64-bit standalone dev build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          DELETE_AFTER: '1'
