name: Build Normal
on:
  push:
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.ref }}-Normal
  cancel-in-progress: true

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clean all artifacts
        uses: c-hive/gha-remove-artifacts@v4
        with:
          age: '60 seconds' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile Flames using mono
        shell: bash
        id: compile
        run: |
          msbuild Flames.sln /p:Configuration=Release
          cp -R bin/Release bin/Release_normal
          rm bin/Release/Flames_.dll
          msbuild Flames/Flames.csproj /p:Configuration=Release /p:DefineConstants=""

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Flames .NET build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release_normal'
          DEST_NAME: 'Flames'
          NOTIFY_MESSAGE: 'Successfully compiled Flames .NET build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
