name: Build TLI
on:
  push:
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.ref }}-TLI
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile FlamesTLI using mono
        shell: bash
        id: compile
        run: |
          msbuild FlamesTLI.sln /p:Configuration=Release
          cp -R bin/Release bin/Release_TLI
          rm bin/Release/FlamesTLI_.dll
          msbuild FlamesTLI/Flames_TLI.csproj /p:Configuration=Release /p:DefineConstants="FLAMES_TLI"

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile Flames .NET TLI build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release_TLI'
          DEST_NAME: 'Flames'
          NOTIFY_MESSAGE: 'Successfully compiled Flames .NET TLI build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          DELETE_AFTER: '1'
